version: "3.7"

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_apps_v6_development
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
  #   container_name: elasticsearch_test
  #   environment:
  #     discovery.type: single-node
  #     ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data
  redis:
    image: redis:7.0.15
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    logging:
      driver: none
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 5s
      retries: 10

  sidekiq:
    build: ./
    command: bundle exec sidekiq
    restart: always
    volumes:
      - ./:/workspace
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: chatting_app_development
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - "db"
      - "web"
      - "redis"
      # - "elasticsearch"

  web:
    image: ruby:3.1
    container_name: chat_app
    working_dir: /chat_apps_v6
    environment:
      DB_USERNAME: root
      DB_PASSWORD: "root"
      DB_NAME: chat_apps_v6_development
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/chat_apps_v6
    ports:
      - "3000:3000"
    depends_on:
      - db 
    command: bash -c "bundle install && rails db:create db:migrate && rails server -b '0.0.0.0'"

volumes:
  db_data:
  bundle:
  redis:

  # es_data:
